
spring:
  datasource:
    url: jdbc:postgresql://192.168.8.45:5432/postgres?currentSchema=test
    username: test
    password: Gauss_234
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: false #关闭缓存

server:
  port: 8081